exclude: '^modules'
repos:
    - repo: git://github.com/antonbabenko/pre-commit-terraform
      rev: v1.43.0
      hooks:
        - id: terraform_fmt
        - id: terraform_docs_replace
        - id: terraform_tfsec
        - id: terraform_tflint
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.1.0
      hooks:
        - id: check-merge-conflict
        - id: end-of-file-fixer
        - id: check-yaml
        - id: detect-aws-credentials
        - id: detect-private-key
